meta-wpe: faad2 now requires commercial license to be whitelisted
Fixes build error:

    ERROR: Nothing PROVIDES 'faad2' (but [...]/gstreamer1.0-plugins-bad_1.14.2.bb DEPENDS on or otherwise requires it)
    faad2 was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST

Signed-off-by: Hugo Hromic <hhromic@gmail.com>