netflix: Remove bogus RPATHs
Use install instead of copy

Fixes package QA errors

package netflix contains bad RPATH
ERROR: QA Issue: package netflix contains bad RPATH
$ORIGIN:/home/ubuntu/work/oe/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/netflix/4.2.2+gitAUTOINC+7194c6520f-r0/build/src/platform/gibbon:
in file
/home/ubuntu/work/oe/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/netflix/4.2.2+gitAUTOINC+7194c6520f-r0/packages-split/netflix/usr/bin/netflix
[rpaths]

Signed-off-by: Khem Raj <raj.khem@gmail.com>