webbridge: fix packaging QA errors due to libproxystubs.so install path
  ERROR: QA Issue: non debug package contains .debug directory: webbridge path work/core2-32-rdk-linux/webbridge/1.0+gitrAUTOINC+6db5934fd1-r0/packages-split/webbridge/usr/lib/webbridge/proxystubs/.debug/libproxystubs.so [debug-files]
  ERROR: QA run found fatal errors. Please consider fixing them.
  ERROR: Function failed: do_package_qa

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>