add missing LICENSE tag
Fixes:
ERROR: onemw/meta-wpe/recipes-core/packagegroups/packagegroup-wpe-boot.bb: This recipe does not have the LICENSE field set (packagegroup-wpe-boot)      | ETA:  00:00:21
ERROR: Failed to parse recipe: onemw/onemw/oe-builds/svp-1/onemw/meta-wpe/recipes-core/packagegroups/packagegroup-wpe-boot.bb